version: '2'
services:
  config-service:
    image: edowon0623/config-service:test
    ports:
      - "8888:8888"
    networks:
      my-network:

  discovery-service:
    image: edowon0623/service-discovery:test
    ports:
      - "8761:8761"
    networks:
      my-network:

  user-service:
    image: edowon0623/user-service:test
    ports:
      - "60000:60000"
    environment:
      spring.cloud.config.uri: http://config-service:8888
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
      logging.file: /api-logs/users-ws.log
    depends_on:
      - config-service
    networks:
      my-network:
#        ipv4_address: 172.18.0.12

networks:
  my-network:
    external: true
    name: my-network